// Generated by delombok at Tue Jan 14 16:25:34 UTC 2025
package gov.cms.fiss.pricers.fqhc.core.tables;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import gov.cms.fiss.pricers.fqhc.core.tables.PaymentRateTableEntry.Fields;
import java.math.BigDecimal;
import java.time.LocalDate;
import javax.annotation.concurrent.Immutable;
import javax.validation.constraints.Digits;

@Immutable
@JsonDeserialize(builder = AddOnRateTableEntry.AddOnRateTableEntryBuilder.class)
@JsonPropertyOrder({Fields.EFFECTIVE_DATE, Fields.RATE_VALUE})
public class AddOnRateTableEntry {

  @JsonPOJOBuilder(withPrefix = "")
  public static class AddOnRateTableEntryBuilder {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private LocalDate effectiveDate;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private BigDecimal rateValue;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    AddOnRateTableEntryBuilder() {
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AddOnRateTableEntry.AddOnRateTableEntryBuilder effectiveDate(final LocalDate effectiveDate) {
      this.effectiveDate = effectiveDate;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AddOnRateTableEntry.AddOnRateTableEntryBuilder rateValue(final BigDecimal rateValue) {
      this.rateValue = rateValue;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AddOnRateTableEntry build() {
      return new AddOnRateTableEntry(this.effectiveDate, this.rateValue);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
      return "AddOnRateTableEntry.AddOnRateTableEntryBuilder(effectiveDate=" + this.effectiveDate + ", rateValue=" + this.rateValue + ")";
    }
  }

  private final LocalDate effectiveDate;
  @Digits(integer = 2, fraction = 4)
  private final BigDecimal rateValue;

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  AddOnRateTableEntry(final LocalDate effectiveDate, final BigDecimal rateValue) {
    this.effectiveDate = effectiveDate;
    this.rateValue = rateValue;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static AddOnRateTableEntry.AddOnRateTableEntryBuilder builder() {
    return new AddOnRateTableEntry.AddOnRateTableEntryBuilder();
  }


  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static final class Fields {
    public static final java.lang.String EFFECTIVE_DATE = "effectiveDate";
    public static final java.lang.String RATE_VALUE = "rateValue";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public LocalDate getEffectiveDate() {
    return this.effectiveDate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getRateValue() {
    return this.rateValue;
  }
}
