// Generated by delombok at Tue Jan 14 16:25:34 UTC 2025
package gov.cms.fiss.pricers.fqhc.core.tables;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import gov.cms.fiss.pricers.fqhc.core.tables.PaymentRateTableEntry.Fields;
import java.math.BigDecimal;
import java.time.LocalDate;
import javax.annotation.concurrent.Immutable;
import javax.validation.constraints.Digits;

@Immutable
@JsonDeserialize(builder = IopPaymentRateLte3TableEntry.IopPaymentRateLte3TableEntryBuilder.class)
@JsonPropertyOrder({Fields.EFFECTIVE_DATE, Fields.RATE_VALUE})
public class IopPaymentRateLte3TableEntry {

  @JsonPOJOBuilder(withPrefix = "")
  public static class IopPaymentRateLte3TableEntryBuilder {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private LocalDate effectiveDate;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private BigDecimal rateValue;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    IopPaymentRateLte3TableEntryBuilder() {
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public IopPaymentRateLte3TableEntry.IopPaymentRateLte3TableEntryBuilder effectiveDate(final LocalDate effectiveDate) {
      this.effectiveDate = effectiveDate;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public IopPaymentRateLte3TableEntry.IopPaymentRateLte3TableEntryBuilder rateValue(final BigDecimal rateValue) {
      this.rateValue = rateValue;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public IopPaymentRateLte3TableEntry build() {
      return new IopPaymentRateLte3TableEntry(this.effectiveDate, this.rateValue);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
      return "IopPaymentRateLte3TableEntry.IopPaymentRateLte3TableEntryBuilder(effectiveDate=" + this.effectiveDate + ", rateValue=" + this.rateValue + ")";
    }
  }

  private final LocalDate effectiveDate;
  // Only 3 digits to left of decimal ex. (248.50)
  @Digits(integer = 3, fraction = 2)
  private final BigDecimal rateValue;

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  IopPaymentRateLte3TableEntry(final LocalDate effectiveDate, final BigDecimal rateValue) {
    this.effectiveDate = effectiveDate;
    this.rateValue = rateValue;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static IopPaymentRateLte3TableEntry.IopPaymentRateLte3TableEntryBuilder builder() {
    return new IopPaymentRateLte3TableEntry.IopPaymentRateLte3TableEntryBuilder();
  }


  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static final class Fields {
    public static final java.lang.String EFFECTIVE_DATE = "effectiveDate";
    public static final java.lang.String RATE_VALUE = "rateValue";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public LocalDate getEffectiveDate() {
    return this.effectiveDate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getRateValue() {
    return this.rateValue;
  }
}
