// Generated by delombok at Thu Mar 06 01:40:35 UTC 2025
package gov.cms.fiss.pricers.hha.core.models;

import gov.cms.fiss.pricers.common.api.annotations.FixedValue;
import java.math.BigDecimal;

public class RevenueRateEntry {
  private String revenueCode; // TB-STDV-REV-CODE
  @FixedValue
  private BigDecimal dollarRateUnits; // WK-REV-DOLL-RATE-UNITS
  @FixedValue
  private BigDecimal standardValueDollarRate; // TB-STDV-REV-DOLL-RATE
  @FixedValue
  private BigDecimal dollarRate; // HHA-REVENUE-DOLL-RATE

  public RevenueRateEntry(String revenueCode, @FixedValue BigDecimal dollarRateUnits, @FixedValue BigDecimal standardValueDollarRate, @FixedValue BigDecimal dollarRate) {
    this.revenueCode = revenueCode;
    this.dollarRateUnits = dollarRateUnits;
    this.standardValueDollarRate = standardValueDollarRate;
    this.dollarRate = dollarRate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getRevenueCode() {
    return this.revenueCode;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getDollarRateUnits() {
    return this.dollarRateUnits;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getStandardValueDollarRate() {
    return this.standardValueDollarRate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getDollarRate() {
    return this.dollarRate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setRevenueCode(final String revenueCode) {
    this.revenueCode = revenueCode;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setDollarRateUnits(final BigDecimal dollarRateUnits) {
    this.dollarRateUnits = dollarRateUnits;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setStandardValueDollarRate(final BigDecimal standardValueDollarRate) {
    this.standardValueDollarRate = standardValueDollarRate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setDollarRate(final BigDecimal dollarRate) {
    this.dollarRate = dollarRate;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof RevenueRateEntry)) return false;
    final RevenueRateEntry other = (RevenueRateEntry) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$revenueCode = this.getRevenueCode();
    final java.lang.Object other$revenueCode = other.getRevenueCode();
    if (this$revenueCode == null ? other$revenueCode != null : !this$revenueCode.equals(other$revenueCode)) return false;
    final java.lang.Object this$dollarRateUnits = this.getDollarRateUnits();
    final java.lang.Object other$dollarRateUnits = other.getDollarRateUnits();
    if (this$dollarRateUnits == null ? other$dollarRateUnits != null : !this$dollarRateUnits.equals(other$dollarRateUnits)) return false;
    final java.lang.Object this$standardValueDollarRate = this.getStandardValueDollarRate();
    final java.lang.Object other$standardValueDollarRate = other.getStandardValueDollarRate();
    if (this$standardValueDollarRate == null ? other$standardValueDollarRate != null : !this$standardValueDollarRate.equals(other$standardValueDollarRate)) return false;
    final java.lang.Object this$dollarRate = this.getDollarRate();
    final java.lang.Object other$dollarRate = other.getDollarRate();
    if (this$dollarRate == null ? other$dollarRate != null : !this$dollarRate.equals(other$dollarRate)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof RevenueRateEntry;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $revenueCode = this.getRevenueCode();
    result = result * PRIME + ($revenueCode == null ? 43 : $revenueCode.hashCode());
    final java.lang.Object $dollarRateUnits = this.getDollarRateUnits();
    result = result * PRIME + ($dollarRateUnits == null ? 43 : $dollarRateUnits.hashCode());
    final java.lang.Object $standardValueDollarRate = this.getStandardValueDollarRate();
    result = result * PRIME + ($standardValueDollarRate == null ? 43 : $standardValueDollarRate.hashCode());
    final java.lang.Object $dollarRate = this.getDollarRate();
    result = result * PRIME + ($dollarRate == null ? 43 : $dollarRate.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public java.lang.String toString() {
    return "RevenueRateEntry(revenueCode=" + this.getRevenueCode() + ", dollarRateUnits=" + this.getDollarRateUnits() + ", standardValueDollarRate=" + this.getStandardValueDollarRate() + ", dollarRate=" + this.getDollarRate() + ")";
  }
}
