// Generated by delombok at Tue Feb 11 06:59:30 UTC 2025
package gov.cms.fiss.pricers.hospice;

import com.fasterxml.jackson.annotation.JsonProperty;
import gov.cms.fiss.pricers.common.application.OpenApiApplicationConfiguration;
import gov.cms.fiss.pricers.common.csv.CsvIngestionConfiguration;

public class HospicePricerConfiguration extends OpenApiApplicationConfiguration {
  @JsonProperty("csv")
  public CsvIngestionConfiguration csvIngestionConfiguration = new CsvIngestionConfiguration();

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public HospicePricerConfiguration() {
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public CsvIngestionConfiguration getCsvIngestionConfiguration() {
    return this.csvIngestionConfiguration;
  }

  @JsonProperty("csv")
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setCsvIngestionConfiguration(final CsvIngestionConfiguration csvIngestionConfiguration) {
    this.csvIngestionConfiguration = csvIngestionConfiguration;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof HospicePricerConfiguration)) return false;
    final HospicePricerConfiguration other = (HospicePricerConfiguration) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    if (!super.equals(o)) return false;
    final java.lang.Object this$csvIngestionConfiguration = this.getCsvIngestionConfiguration();
    final java.lang.Object other$csvIngestionConfiguration = other.getCsvIngestionConfiguration();
    if (this$csvIngestionConfiguration == null ? other$csvIngestionConfiguration != null : !this$csvIngestionConfiguration.equals(other$csvIngestionConfiguration)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof HospicePricerConfiguration;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = super.hashCode();
    final java.lang.Object $csvIngestionConfiguration = this.getCsvIngestionConfiguration();
    result = result * PRIME + ($csvIngestionConfiguration == null ? 43 : $csvIngestionConfiguration.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public java.lang.String toString() {
    return "HospicePricerConfiguration(csvIngestionConfiguration=" + this.getCsvIngestionConfiguration() + ")";
  }
}
