// Generated by delombok at Tue Jan 14 16:25:34 UTC 2025
package gov.cms.fiss.pricers.fqhc.core.daily;

import gov.cms.fiss.pricers.common.api.annotations.FixedValue;
import java.math.BigDecimal;

public final class DailyRates {
  // Holds the dailyBaseRate until the line is confirmed valid and we need to either create
  // a new Daily Sum or add to an existing one
  @FixedValue
  private final BigDecimal dailyBaseRate;
  // Holds the dailyBaseRate until the line is confirmed valid and we need to either create
  // a new Daily Sum or add to an existing one
  @FixedValue
  private final BigDecimal dailyAddRate;
  // Holds the dailyBaseRate until the line is confirmed valid and we need to either create
  // a new Daily Sum or add to an existing one
  @FixedValue
  private final BigDecimal dailyIopRateLte3;
  @FixedValue
  private final BigDecimal dailyIopRateGte4;
  @FixedValue
  private final BigDecimal dailyGafRate;

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public DailyRates(final BigDecimal dailyBaseRate, final BigDecimal dailyAddRate, final BigDecimal dailyIopRateLte3, final BigDecimal dailyIopRateGte4, final BigDecimal dailyGafRate) {
    this.dailyBaseRate = dailyBaseRate;
    this.dailyAddRate = dailyAddRate;
    this.dailyIopRateLte3 = dailyIopRateLte3;
    this.dailyIopRateGte4 = dailyIopRateGte4;
    this.dailyGafRate = dailyGafRate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getDailyBaseRate() {
    return this.dailyBaseRate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getDailyAddRate() {
    return this.dailyAddRate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getDailyIopRateLte3() {
    return this.dailyIopRateLte3;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getDailyIopRateGte4() {
    return this.dailyIopRateGte4;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getDailyGafRate() {
    return this.dailyGafRate;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof DailyRates)) return false;
    final DailyRates other = (DailyRates) o;
    final java.lang.Object this$dailyBaseRate = this.getDailyBaseRate();
    final java.lang.Object other$dailyBaseRate = other.getDailyBaseRate();
    if (this$dailyBaseRate == null ? other$dailyBaseRate != null : !this$dailyBaseRate.equals(other$dailyBaseRate)) return false;
    final java.lang.Object this$dailyAddRate = this.getDailyAddRate();
    final java.lang.Object other$dailyAddRate = other.getDailyAddRate();
    if (this$dailyAddRate == null ? other$dailyAddRate != null : !this$dailyAddRate.equals(other$dailyAddRate)) return false;
    final java.lang.Object this$dailyIopRateLte3 = this.getDailyIopRateLte3();
    final java.lang.Object other$dailyIopRateLte3 = other.getDailyIopRateLte3();
    if (this$dailyIopRateLte3 == null ? other$dailyIopRateLte3 != null : !this$dailyIopRateLte3.equals(other$dailyIopRateLte3)) return false;
    final java.lang.Object this$dailyIopRateGte4 = this.getDailyIopRateGte4();
    final java.lang.Object other$dailyIopRateGte4 = other.getDailyIopRateGte4();
    if (this$dailyIopRateGte4 == null ? other$dailyIopRateGte4 != null : !this$dailyIopRateGte4.equals(other$dailyIopRateGte4)) return false;
    final java.lang.Object this$dailyGafRate = this.getDailyGafRate();
    final java.lang.Object other$dailyGafRate = other.getDailyGafRate();
    if (this$dailyGafRate == null ? other$dailyGafRate != null : !this$dailyGafRate.equals(other$dailyGafRate)) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $dailyBaseRate = this.getDailyBaseRate();
    result = result * PRIME + ($dailyBaseRate == null ? 43 : $dailyBaseRate.hashCode());
    final java.lang.Object $dailyAddRate = this.getDailyAddRate();
    result = result * PRIME + ($dailyAddRate == null ? 43 : $dailyAddRate.hashCode());
    final java.lang.Object $dailyIopRateLte3 = this.getDailyIopRateLte3();
    result = result * PRIME + ($dailyIopRateLte3 == null ? 43 : $dailyIopRateLte3.hashCode());
    final java.lang.Object $dailyIopRateGte4 = this.getDailyIopRateGte4();
    result = result * PRIME + ($dailyIopRateGte4 == null ? 43 : $dailyIopRateGte4.hashCode());
    final java.lang.Object $dailyGafRate = this.getDailyGafRate();
    result = result * PRIME + ($dailyGafRate == null ? 43 : $dailyGafRate.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public java.lang.String toString() {
    return "DailyRates(dailyBaseRate=" + this.getDailyBaseRate() + ", dailyAddRate=" + this.getDailyAddRate() + ", dailyIopRateLte3=" + this.getDailyIopRateLte3() + ", dailyIopRateGte4=" + this.getDailyIopRateGte4() + ", dailyGafRate=" + this.getDailyGafRate() + ")";
  }
}
