// Generated by delombok at Thu Feb 13 23:37:29 UTC 2025
package gov.cms.fiss.pricers.ipps.core.tables;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import gov.cms.fiss.pricers.ipps.core.tables.MidnightTableEntry.Fields;
import java.math.BigDecimal;
import javax.annotation.concurrent.Immutable;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Pattern;

@Immutable
@JsonDeserialize(builder = MidnightTableEntry.MidnightTableEntryBuilder.class)
@JsonPropertyOrder({Fields.MSA, Fields.ADJUSTMENT_FACTOR})
public class MidnightTableEntry {

  @JsonPOJOBuilder(withPrefix = "")
  public static class MidnightTableEntryBuilder {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private BigDecimal adjustmentFactor;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private String msa;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    MidnightTableEntryBuilder() {
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MidnightTableEntry.MidnightTableEntryBuilder adjustmentFactor(final BigDecimal adjustmentFactor) {
      this.adjustmentFactor = adjustmentFactor;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MidnightTableEntry.MidnightTableEntryBuilder msa(final String msa) {
      this.msa = msa;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MidnightTableEntry build() {
      return new MidnightTableEntry(this.adjustmentFactor, this.msa);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
      return "MidnightTableEntry.MidnightTableEntryBuilder(adjustmentFactor=" + this.adjustmentFactor + ", msa=" + this.msa + ")";
    }
  }

  @Digits(integer = 2, fraction = 6)
  private final BigDecimal adjustmentFactor;
  @Pattern(regexp = "\\d{4}")
  private final String msa;

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  MidnightTableEntry(final BigDecimal adjustmentFactor, final String msa) {
    this.adjustmentFactor = adjustmentFactor;
    this.msa = msa;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static MidnightTableEntry.MidnightTableEntryBuilder builder() {
    return new MidnightTableEntry.MidnightTableEntryBuilder();
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getAdjustmentFactor() {
    return this.adjustmentFactor;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getMsa() {
    return this.msa;
  }


  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static final class Fields {
    public static final java.lang.String ADJUSTMENT_FACTOR = "adjustmentFactor";
    public static final java.lang.String MSA = "msa";
  }
}
