// Generated by delombok at Thu Feb 13 23:37:29 UTC 2025
package gov.cms.fiss.pricers.ipps.core.tables;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import gov.cms.fiss.pricers.ipps.core.tables.PrevYearWIFY19TableEntry.Fields;
import java.math.BigDecimal;
import javax.annotation.concurrent.Immutable;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Pattern;

@Immutable
@JsonDeserialize(builder = PrevYearWIFY19TableEntry.PrevYearWIFY19TableEntryBuilder.class)
@JsonPropertyOrder({Fields.PROVIDER, Fields.PREV_WAGE_INDEX})
public class PrevYearWIFY19TableEntry {

  @JsonPOJOBuilder(withPrefix = "")
  public static class PrevYearWIFY19TableEntryBuilder {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private BigDecimal prevWageIndex;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private String provider;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    PrevYearWIFY19TableEntryBuilder() {
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PrevYearWIFY19TableEntry.PrevYearWIFY19TableEntryBuilder prevWageIndex(final BigDecimal prevWageIndex) {
      this.prevWageIndex = prevWageIndex;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PrevYearWIFY19TableEntry.PrevYearWIFY19TableEntryBuilder provider(final String provider) {
      this.provider = provider;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public PrevYearWIFY19TableEntry build() {
      return new PrevYearWIFY19TableEntry(this.prevWageIndex, this.provider);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
      return "PrevYearWIFY19TableEntry.PrevYearWIFY19TableEntryBuilder(prevWageIndex=" + this.prevWageIndex + ", provider=" + this.provider + ")";
    }
  }

  @Digits(integer = 2, fraction = 4)
  private final BigDecimal prevWageIndex;
  @Pattern(regexp = "[A-Z0-9]{6}")
  private final String provider;

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  PrevYearWIFY19TableEntry(final BigDecimal prevWageIndex, final String provider) {
    this.prevWageIndex = prevWageIndex;
    this.provider = provider;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static PrevYearWIFY19TableEntry.PrevYearWIFY19TableEntryBuilder builder() {
    return new PrevYearWIFY19TableEntry.PrevYearWIFY19TableEntryBuilder();
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getPrevWageIndex() {
    return this.prevWageIndex;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getProvider() {
    return this.provider;
  }


  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static final class Fields {
    public static final java.lang.String PREV_WAGE_INDEX = "prevWageIndex";
    public static final java.lang.String PROVIDER = "provider";
  }
}
