// Generated by delombok at Thu Feb 13 23:37:29 UTC 2025
package gov.cms.fiss.pricers.ipps.core.tables;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import gov.cms.fiss.pricers.ipps.core.tables.RuralFloorTableEntry.Fields;
import java.math.BigDecimal;
import javax.annotation.concurrent.Immutable;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Pattern;

@Immutable
@JsonDeserialize(builder = RuralFloorTableEntry.RuralFloorTableEntryBuilder.class)
@JsonPropertyOrder({Fields.CBSA, Fields.WAGE_INDEX})
public class RuralFloorTableEntry {

  @JsonPOJOBuilder(withPrefix = "")
  public static class RuralFloorTableEntryBuilder {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private String cbsa;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private BigDecimal wageIndex;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    RuralFloorTableEntryBuilder() {
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RuralFloorTableEntry.RuralFloorTableEntryBuilder cbsa(final String cbsa) {
      this.cbsa = cbsa;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RuralFloorTableEntry.RuralFloorTableEntryBuilder wageIndex(final BigDecimal wageIndex) {
      this.wageIndex = wageIndex;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RuralFloorTableEntry build() {
      return new RuralFloorTableEntry(this.cbsa, this.wageIndex);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
      return "RuralFloorTableEntry.RuralFloorTableEntryBuilder(cbsa=" + this.cbsa + ", wageIndex=" + this.wageIndex + ")";
    }
  }

  @Pattern(regexp = "\\d{2}|\\d{5}")
  private final String cbsa;
  @Digits(integer = 2, fraction = 4)
  private final BigDecimal wageIndex;

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  RuralFloorTableEntry(final String cbsa, final BigDecimal wageIndex) {
    this.cbsa = cbsa;
    this.wageIndex = wageIndex;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static RuralFloorTableEntry.RuralFloorTableEntryBuilder builder() {
    return new RuralFloorTableEntry.RuralFloorTableEntryBuilder();
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getCbsa() {
    return this.cbsa;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getWageIndex() {
    return this.wageIndex;
  }


  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static final class Fields {
    public static final java.lang.String CBSA = "cbsa";
    public static final java.lang.String WAGE_INDEX = "wageIndex";
  }
}
