// Generated by delombok at Tue Feb 18 20:49:31 UTC 2025
package gov.cms.fiss.pricers.ipf.core.tables;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import gov.cms.fiss.pricers.common.api.serialization.BigDecimalScale;
import gov.cms.fiss.pricers.ipf.core.tables.CodeFirstTableEntry.Fields;
import java.math.BigDecimal;
import javax.annotation.concurrent.Immutable;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Pattern;

/**
 * Model for the Code First CSV file.
 */
@Immutable
@JsonDeserialize(builder = CodeFirstTableEntry.CodeFirstTableEntryBuilder.class)
@JsonPropertyOrder({Fields.CODE, Fields.FACTOR})
public class CodeFirstTableEntry {

  @JsonPOJOBuilder(withPrefix = "")
  public static class CodeFirstTableEntryBuilder {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private String code;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private BigDecimal factor;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    CodeFirstTableEntryBuilder() {
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CodeFirstTableEntry.CodeFirstTableEntryBuilder code(final String code) {
      this.code = code;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CodeFirstTableEntry.CodeFirstTableEntryBuilder factor(final BigDecimal factor) {
      this.factor = factor;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public CodeFirstTableEntry build() {
      return new CodeFirstTableEntry(this.code, this.factor);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
      return "CodeFirstTableEntry.CodeFirstTableEntryBuilder(code=" + this.code + ", factor=" + this.factor + ")";
    }
  }

  @Pattern(regexp = "[A-Z][A-Z0-9]{2,5}")
  private final String code;
  @Digits(integer = 1, fraction = 2)
  @BigDecimalScale
  @DecimalMin("0.00")
  @DecimalMax("9.99")
  private final BigDecimal factor;

  public CodeFirstTableEntryBuilder copyBuilder() {
    return new CodeFirstTableEntryBuilder().code(code).factor(factor);
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  CodeFirstTableEntry(final String code, final BigDecimal factor) {
    this.code = code;
    this.factor = factor;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static CodeFirstTableEntry.CodeFirstTableEntryBuilder builder() {
    return new CodeFirstTableEntry.CodeFirstTableEntryBuilder();
  }


  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static final class Fields {
    public static final java.lang.String CODE = "code";
    public static final java.lang.String FACTOR = "factor";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getCode() {
    return this.code;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getFactor() {
    return this.factor;
  }
}
