// Generated by delombok at Tue Feb 18 20:49:31 UTC 2025
package gov.cms.fiss.pricers.ipf.core.tables;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import gov.cms.fiss.pricers.ipf.core.tables.ComorbidityTableEntry.Fields;
import javax.annotation.concurrent.Immutable;
import javax.validation.constraints.Pattern;

/**
 * Model for the Comorbidity CSV file.
 */
@Immutable
@JsonDeserialize(builder = ComorbidityTableEntry.ComorbidityTableEntryBuilder.class)
@JsonPropertyOrder({Fields.CODE, Fields.CATEGORY})
public class ComorbidityTableEntry {

  @JsonPOJOBuilder(withPrefix = "")
  public static class ComorbidityTableEntryBuilder {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private String code;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private String category;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    ComorbidityTableEntryBuilder() {
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ComorbidityTableEntry.ComorbidityTableEntryBuilder code(final String code) {
      this.code = code;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ComorbidityTableEntry.ComorbidityTableEntryBuilder category(final String category) {
      this.category = category;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ComorbidityTableEntry build() {
      return new ComorbidityTableEntry(this.code, this.category);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
      return "ComorbidityTableEntry.ComorbidityTableEntryBuilder(code=" + this.code + ", category=" + this.category + ")";
    }
  }

  @Pattern(regexp = "[A-Za-z0-9]{3,7}")
  private final String code;
  @Pattern(regexp = "[1-9][0-8P]?")
  private final String category;

  public ComorbidityTableEntryBuilder copyBuilder() {
    return new ComorbidityTableEntryBuilder().code(code).category(category);
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  ComorbidityTableEntry(final String code, final String category) {
    this.code = code;
    this.category = category;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static ComorbidityTableEntry.ComorbidityTableEntryBuilder builder() {
    return new ComorbidityTableEntry.ComorbidityTableEntryBuilder();
  }


  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static final class Fields {
    public static final java.lang.String CODE = "code";
    public static final java.lang.String CATEGORY = "category";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getCode() {
    return this.code;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getCategory() {
    return this.category;
  }
}
