// Generated by delombok at Tue Feb 18 20:49:31 UTC 2025
package gov.cms.fiss.pricers.ipf.core.tables;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonFormat.Shape;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import gov.cms.fiss.pricers.ipf.core.tables.ProcedureTableEntry.Fields;
import java.time.LocalDate;
import javax.annotation.concurrent.Immutable;
import javax.validation.constraints.Pattern;

/**
 * Model for the Comorbidity CSV file.
 */
@Immutable
@JsonDeserialize(builder = ProcedureTableEntry.ProcedureTableEntryBuilder.class)
@JsonPropertyOrder({Fields.CODE, Fields.CATEGORY})
public class ProcedureTableEntry {

  @JsonPOJOBuilder(withPrefix = "")
  public static class ProcedureTableEntryBuilder {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private String code;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private String category;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private LocalDate effectiveDate;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    ProcedureTableEntryBuilder() {
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProcedureTableEntry.ProcedureTableEntryBuilder code(final String code) {
      this.code = code;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProcedureTableEntry.ProcedureTableEntryBuilder category(final String category) {
      this.category = category;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @JsonFormat(shape = Shape.STRING, pattern = "yyyyMMdd")
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProcedureTableEntry.ProcedureTableEntryBuilder effectiveDate(final LocalDate effectiveDate) {
      this.effectiveDate = effectiveDate;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProcedureTableEntry build() {
      return new ProcedureTableEntry(this.code, this.category, this.effectiveDate);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
      return "ProcedureTableEntry.ProcedureTableEntryBuilder(code=" + this.code + ", category=" + this.category + ", effectiveDate=" + this.effectiveDate + ")";
    }
  }

  @Pattern(regexp = "[A-Za-z0-9]{3,7}")
  private final String code;
  @Pattern(regexp = "[1-9][0-8P]?")
  private final String category;
  @JsonFormat(shape = Shape.STRING, pattern = "yyyyMMdd")
  private final LocalDate effectiveDate;

  public ProcedureTableEntryBuilder copyBuilder() {
    return new ProcedureTableEntryBuilder().code(code).category(category).effectiveDate(effectiveDate);
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  ProcedureTableEntry(final String code, final String category, final LocalDate effectiveDate) {
    this.code = code;
    this.category = category;
    this.effectiveDate = effectiveDate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static ProcedureTableEntry.ProcedureTableEntryBuilder builder() {
    return new ProcedureTableEntry.ProcedureTableEntryBuilder();
  }


  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static final class Fields {
    public static final java.lang.String CODE = "code";
    public static final java.lang.String CATEGORY = "category";
    public static final java.lang.String EFFECTIVE_DATE = "effectiveDate";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getCode() {
    return this.code;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public String getCategory() {
    return this.category;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public LocalDate getEffectiveDate() {
    return this.effectiveDate;
  }
}
