// Generated by delombok at Mon Sep 30 19:32:36 UTC 2024
package gov.cms.fiss.pricers.ltch.core.models;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonFormat.Shape;
import java.math.BigDecimal;
import java.time.LocalDate;

public class LtchWageIndexTableEntry {
  private Integer cbsa;
  @JsonFormat(shape = Shape.STRING, pattern = "yyyyMMdd")
  private LocalDate effectiveDate;
  private BigDecimal ltchWageIndex1;
  private BigDecimal ltchWageIndex2;
  private BigDecimal ltchWageIndex3;

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public Integer getCbsa() {
    return this.cbsa;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public LocalDate getEffectiveDate() {
    return this.effectiveDate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getLtchWageIndex1() {
    return this.ltchWageIndex1;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getLtchWageIndex2() {
    return this.ltchWageIndex2;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getLtchWageIndex3() {
    return this.ltchWageIndex3;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setCbsa(final Integer cbsa) {
    this.cbsa = cbsa;
  }

  @JsonFormat(shape = Shape.STRING, pattern = "yyyyMMdd")
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setEffectiveDate(final LocalDate effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setLtchWageIndex1(final BigDecimal ltchWageIndex1) {
    this.ltchWageIndex1 = ltchWageIndex1;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setLtchWageIndex2(final BigDecimal ltchWageIndex2) {
    this.ltchWageIndex2 = ltchWageIndex2;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setLtchWageIndex3(final BigDecimal ltchWageIndex3) {
    this.ltchWageIndex3 = ltchWageIndex3;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof LtchWageIndexTableEntry)) return false;
    final LtchWageIndexTableEntry other = (LtchWageIndexTableEntry) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$cbsa = this.getCbsa();
    final java.lang.Object other$cbsa = other.getCbsa();
    if (this$cbsa == null ? other$cbsa != null : !this$cbsa.equals(other$cbsa)) return false;
    final java.lang.Object this$effectiveDate = this.getEffectiveDate();
    final java.lang.Object other$effectiveDate = other.getEffectiveDate();
    if (this$effectiveDate == null ? other$effectiveDate != null : !this$effectiveDate.equals(other$effectiveDate)) return false;
    final java.lang.Object this$ltchWageIndex1 = this.getLtchWageIndex1();
    final java.lang.Object other$ltchWageIndex1 = other.getLtchWageIndex1();
    if (this$ltchWageIndex1 == null ? other$ltchWageIndex1 != null : !this$ltchWageIndex1.equals(other$ltchWageIndex1)) return false;
    final java.lang.Object this$ltchWageIndex2 = this.getLtchWageIndex2();
    final java.lang.Object other$ltchWageIndex2 = other.getLtchWageIndex2();
    if (this$ltchWageIndex2 == null ? other$ltchWageIndex2 != null : !this$ltchWageIndex2.equals(other$ltchWageIndex2)) return false;
    final java.lang.Object this$ltchWageIndex3 = this.getLtchWageIndex3();
    final java.lang.Object other$ltchWageIndex3 = other.getLtchWageIndex3();
    if (this$ltchWageIndex3 == null ? other$ltchWageIndex3 != null : !this$ltchWageIndex3.equals(other$ltchWageIndex3)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof LtchWageIndexTableEntry;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $cbsa = this.getCbsa();
    result = result * PRIME + ($cbsa == null ? 43 : $cbsa.hashCode());
    final java.lang.Object $effectiveDate = this.getEffectiveDate();
    result = result * PRIME + ($effectiveDate == null ? 43 : $effectiveDate.hashCode());
    final java.lang.Object $ltchWageIndex1 = this.getLtchWageIndex1();
    result = result * PRIME + ($ltchWageIndex1 == null ? 43 : $ltchWageIndex1.hashCode());
    final java.lang.Object $ltchWageIndex2 = this.getLtchWageIndex2();
    result = result * PRIME + ($ltchWageIndex2 == null ? 43 : $ltchWageIndex2.hashCode());
    final java.lang.Object $ltchWageIndex3 = this.getLtchWageIndex3();
    result = result * PRIME + ($ltchWageIndex3 == null ? 43 : $ltchWageIndex3.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public java.lang.String toString() {
    return "LtchWageIndexTableEntry(cbsa=" + this.getCbsa() + ", effectiveDate=" + this.getEffectiveDate() + ", ltchWageIndex1=" + this.getLtchWageIndex1() + ", ltchWageIndex2=" + this.getLtchWageIndex2() + ", ltchWageIndex3=" + this.getLtchWageIndex3() + ")";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public LtchWageIndexTableEntry() {
  }
}
