// Generated by delombok at Thu Mar 06 01:40:35 UTC 2025
package gov.cms.fiss.pricers.hha.resources;

import gov.cms.fiss.pricers.common.api.CbsaWageIndexData;
import gov.cms.fiss.pricers.hha.core.tables.CbsaWageIndexEntry;
import gov.cms.fiss.pricers.hha.core.tables.DataTables;
import gov.cms.fiss.pricers.hha.resources.mapping.CbsaWageIndexDataMapper;
import java.time.LocalDate;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.NavigableMap;
import java.util.Optional;
import java.util.function.IntFunction;
import java.util.stream.Collectors;

public final class HhaExtractionUtil {
  public static final IntFunction<List<CbsaWageIndexData>> CBSA_EXTRACTOR = pricerYear -> {
    final Optional<Map<String, NavigableMap<LocalDate, CbsaWageIndexEntry>>> matchingData = Optional.ofNullable(DataTables.forYear(pricerYear).getCbsaTable());
    return matchingData.map(Map::entrySet).stream().flatMap(s -> s.stream().map(Entry::getValue)).map(Map::entrySet).flatMap(Collection::stream).map(Entry::getValue).map(CbsaWageIndexDataMapper.INSTANCE::mapToCbsaWageIndexData).collect(Collectors.toList());
  };

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  private HhaExtractionUtil() {
    throw new java.lang.UnsupportedOperationException("This is a utility class and cannot be instantiated");
  }
}
