// Generated by delombok at Thu Sep 12 18:33:21 UTC 2024
package gov.cms.fiss.pricers.snf.core.tables;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import gov.cms.fiss.pricers.snf.core.tables.VariablePerDiemEntry.Fields;
import java.math.BigDecimal;
import javax.annotation.concurrent.Immutable;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;

@Immutable
@JsonDeserialize(builder = VariablePerDiemEntry.VariablePerDiemEntryBuilder.class)
@JsonPropertyOrder({Fields.DAY, Fields.PHYSICAL_AND_OCCUPATIONAL_ADJ_FACTOR, Fields.NON_THERAPY_ANCILLARY_ADJ_FACTOR})
public class VariablePerDiemEntry {

  @JsonPOJOBuilder(withPrefix = "")
  public static class VariablePerDiemEntryBuilder {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private int day;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private BigDecimal physicalAndOccupationalAdjFactor;
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private BigDecimal nonTherapyAncillaryAdjFactor;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    VariablePerDiemEntryBuilder() {
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public VariablePerDiemEntry.VariablePerDiemEntryBuilder day(final int day) {
      this.day = day;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public VariablePerDiemEntry.VariablePerDiemEntryBuilder physicalAndOccupationalAdjFactor(final BigDecimal physicalAndOccupationalAdjFactor) {
      this.physicalAndOccupationalAdjFactor = physicalAndOccupationalAdjFactor;
      return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public VariablePerDiemEntry.VariablePerDiemEntryBuilder nonTherapyAncillaryAdjFactor(final BigDecimal nonTherapyAncillaryAdjFactor) {
      this.nonTherapyAncillaryAdjFactor = nonTherapyAncillaryAdjFactor;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public VariablePerDiemEntry build() {
      return new VariablePerDiemEntry(this.day, this.physicalAndOccupationalAdjFactor, this.nonTherapyAncillaryAdjFactor);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
      return "VariablePerDiemEntry.VariablePerDiemEntryBuilder(day=" + this.day + ", physicalAndOccupationalAdjFactor=" + this.physicalAndOccupationalAdjFactor + ", nonTherapyAncillaryAdjFactor=" + this.nonTherapyAncillaryAdjFactor + ")";
    }
  }

  @Min(1)
  @Max(100)
  private final int day;
  @Digits(integer = 1, fraction = 2)
  @DecimalMin("0.0")
  @DecimalMax("9.99")
  private final BigDecimal physicalAndOccupationalAdjFactor;
  @Digits(integer = 1, fraction = 2)
  @DecimalMin("0.0")
  @DecimalMax("9.99")
  private final BigDecimal nonTherapyAncillaryAdjFactor;

  public VariablePerDiemEntryBuilder copyBuilder() {
    return VariablePerDiemEntry.builder().day(getDay()).physicalAndOccupationalAdjFactor(getPhysicalAndOccupationalAdjFactor()).nonTherapyAncillaryAdjFactor(getNonTherapyAncillaryAdjFactor());
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  VariablePerDiemEntry(final int day, final BigDecimal physicalAndOccupationalAdjFactor, final BigDecimal nonTherapyAncillaryAdjFactor) {
    this.day = day;
    this.physicalAndOccupationalAdjFactor = physicalAndOccupationalAdjFactor;
    this.nonTherapyAncillaryAdjFactor = nonTherapyAncillaryAdjFactor;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static VariablePerDiemEntry.VariablePerDiemEntryBuilder builder() {
    return new VariablePerDiemEntry.VariablePerDiemEntryBuilder();
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof VariablePerDiemEntry)) return false;
    final VariablePerDiemEntry other = (VariablePerDiemEntry) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    if (this.getDay() != other.getDay()) return false;
    final java.lang.Object this$physicalAndOccupationalAdjFactor = this.getPhysicalAndOccupationalAdjFactor();
    final java.lang.Object other$physicalAndOccupationalAdjFactor = other.getPhysicalAndOccupationalAdjFactor();
    if (this$physicalAndOccupationalAdjFactor == null ? other$physicalAndOccupationalAdjFactor != null : !this$physicalAndOccupationalAdjFactor.equals(other$physicalAndOccupationalAdjFactor)) return false;
    final java.lang.Object this$nonTherapyAncillaryAdjFactor = this.getNonTherapyAncillaryAdjFactor();
    final java.lang.Object other$nonTherapyAncillaryAdjFactor = other.getNonTherapyAncillaryAdjFactor();
    if (this$nonTherapyAncillaryAdjFactor == null ? other$nonTherapyAncillaryAdjFactor != null : !this$nonTherapyAncillaryAdjFactor.equals(other$nonTherapyAncillaryAdjFactor)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof VariablePerDiemEntry;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + this.getDay();
    final java.lang.Object $physicalAndOccupationalAdjFactor = this.getPhysicalAndOccupationalAdjFactor();
    result = result * PRIME + ($physicalAndOccupationalAdjFactor == null ? 43 : $physicalAndOccupationalAdjFactor.hashCode());
    final java.lang.Object $nonTherapyAncillaryAdjFactor = this.getNonTherapyAncillaryAdjFactor();
    result = result * PRIME + ($nonTherapyAncillaryAdjFactor == null ? 43 : $nonTherapyAncillaryAdjFactor.hashCode());
    return result;
  }


  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public static final class Fields {
    public static final java.lang.String DAY = "day";
    public static final java.lang.String PHYSICAL_AND_OCCUPATIONAL_ADJ_FACTOR = "physicalAndOccupationalAdjFactor";
    public static final java.lang.String NON_THERAPY_ANCILLARY_ADJ_FACTOR = "nonTherapyAncillaryAdjFactor";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int getDay() {
    return this.day;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getPhysicalAndOccupationalAdjFactor() {
    return this.physicalAndOccupationalAdjFactor;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BigDecimal getNonTherapyAncillaryAdjFactor() {
    return this.nonTherapyAncillaryAdjFactor;
  }
}
